<?php
new Demo\Demo();
new TopSlider\TopSlider();
new ProductsBlock\ProductsBlock();
new Faq\Faq();
new DeliveryRow\DeliveryRow();
new WhatPayReceive\WhatPayReceive();
new AboutUs\AboutUs();
new NewsBlogs\NewsBlogs();
new Contacts\Contacts();
new Gallery\Gallery();
new PrivacyPolicy\PrivacyPolicy();
new PublicOffer\PublicOffer();
new ReturnPolicy\ReturnPolicy();
new BreadcrumbsTitleCats\BreadcrumbsTitleCats();
new ProductCategory\ProductCategory();
new SaleCategories\SaleCategories();
new Menu\Menu();
new Sale\Sale();
